### ISSUE TITLE
Setup Function To Allow Posts To Queue

### ISSUE THREAD

**Issue by noce2cicd** [math-dojo/question-queue-function#1]
As an authorised calling client via the API Gateway, I can request that a message be placed on the queue for processing later.

- [x] Azure SDK is set up to enable posting to the queue from the functionApp
- [x] Azure credentials needed by the functionApp to publish to the queue are appropriately hidden
- [x] Function App is deployed by default in 3 environments
- [x] The functionApp is deployed along with an associated queue

Issue source:
_Originally posted by @noce2cicd in https://github.com/math-dojo/single-page-web-app/issues/34#issuecomment-655914281_

**Comment by noce2** [comment]
Hey @aakano684 I was checking whether we could tick the final criteria on this piece. Does the pipeline for the function deploy the queue as well? It seems like it only does the function?

**Comment by aakano684** [comment]
The pipeline does deploy the queue so I'm going to close it now. High level design card https://github.com/orgs/math-dojo/projects/2#card-46881698 details some additions we have planned for this project.
